name: Deprecations Bot

on:
  pull_request:
    branches:
      - main
    types:
      [closed]


permissions:
  contents: read

jobs:
  deprecation_update:
    permissions:
      issues: write
    if: >-
      contains(github.event.pull_request.labels.*.name, 'Deprecate') && github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      run: |
        echo "Adding deprecation pr number to issue"
        echo ${{ github.event.pull_request.merged }} == false
        ISSUENR=2
        export PR=${{ github.event.pull_request.number }}
        BODY=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/issues/${ISSUENR} |
          python3 -c "import sys, json, os; x = {'body': json.load(sys.stdin)['body']}; pr = os.environ['PR']; x['body'] += f'\n- [ ] #{pr}'; print(json.dumps(x))")
        echo ${BODY}
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X PATCH -d "${BODY}" https://api.github.com/repos/${{ github.repository }}/issues/${ISSUENR}
